name: 'Issue Comment'

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  deploy:
    name: 'Comment on Pull Request'
    runs-on: ubuntu-20.04
    if: github.actor != 'dependabot[bot]' && (github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository)
    steps:
      - uses: actions/checkout@v3

      - uses: ./
        name: Template Comment
        with:
          action: 'create-clean'
          id: example
          issue-number: ${{ github.event.pull_request.number }}
          template: '.github/pr-comment-template.hbs'
          token: ${{ secrets.GITHUB_TOKEN }}
          template-inputs: |
            {
              "firstName": "Bob",
              "lastName": "Marley"
            }

      - uses: ./
        name: Body Comment
        with:
          action: 'create-clean'
          id: example2
          issue-number: ${{ github.event.pull_request.number }}
          body: 'Test comment'
          token: ${{ secrets.GITHUB_TOKEN }}
